import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Icon} from './icons';
import {LinkPreview} from './LinkPreview';
export function DocumentReader({graph,node,module,cluster,onCluster,onGo,onClose,onPreview}){
 const ref=useRef(null);const [full,setFull]=useState(false);const [copy,setCopy]=useState('');
 useEffect(()=>{const scroll=()=>{const part=location.hash.split('/')[3];if(!part)return;requestAnimationFrame(()=>{const id=decodeURIComponent(part);const target=[...ref.current.querySelectorAll('[id]')].find(el=>el.id===id);target?.scrollIntoView({block:'start'});});};scroll();window.addEventListener('hashchange',scroll);return()=>window.removeEventListener('hashchange',scroll);},[node.id,node.html]);
 useEffect(()=>{const wrap=ref.current.closest('.analysis-wrap');wrap.classList.toggle('full-reader',full);return()=>wrap.classList.remove('full-reader');},[full]);
 const article=useMemo(()=><article className="markdown" dangerouslySetInnerHTML={{__html:node.html}}/>,[node.html]);
 const follow=ids=>[...new Set(ids)].map(id=>graph.index.get(id)).filter(n=>n&&n.id!==node.id).map(n=><button key={n.id} className="read-relation" data-preview-href={`#/doc/${encodeURIComponent(n.id)}`} onClick={()=>onGo(n.id)}><i style={{background:graph.kinds[n.kind].color}}/>{n.title}<Icon name="arrow" size={12}/></button>);
 const handleClick=async e=>{const button=e.target.closest('.copy-code');if(!button)return;try{await navigator.clipboard.writeText(button.closest('.code-block').querySelector('code').textContent);button.textContent='已复制';setTimeout(()=>button.textContent='复制',1800);}catch{setCopy('请手动选择代码进行复制。');}};
 return <section className="analysis glass document-reader" ref={ref}><div className="an-float">文档阅读 <em>Read document · {module.title}</em></div><div className="an-scroll" onClick={handleClick}><div className="an-head"><span className="an-cat"><span className="an-cat-icon" style={{'--kc':graph.kinds[node.kind].color}}><Icon name={module.icon} size={15}/></span><span className="read-category"><span className="read-property-label">分类</span><button className="read-category-link" aria-label={`查看分类 ${node.category || '未分类'} 的集群`} aria-pressed={cluster?.category === module.id} onClick={()=>{setFull(false);onCluster({category:module.id});}}>{node.category || '未分类'}</button></span></span><div className="read-actions"><button className="icon-btn" aria-label="切换专注阅读" title="专注阅读" onClick={()=>setFull(v=>!v)}><Icon name="expand" size={14}/></button><button className="icon-btn" aria-label="关闭文档" onClick={onClose}><Icon name="close" size={14}/></button></div></div><div className="an-title-row"><h2>{node.title}</h2></div><p className="read-meta">{node.updated?'更新于 '+node.updated+' · ':''}知识笔记 · {Math.max(1,Math.ceil(node.body.length/500))} 分钟阅读</p>{node.tags?.length>0&&<dl className="read-properties"><div><dt>标签</dt><dd>{node.tags.map(tag=><button className="read-tag" key={tag} aria-label={`查看标签 ${tag} 的集群`} aria-pressed={cluster?.tag === tag} onClick={()=>{setFull(false);onCluster({tag});}}>{tag}</button>)}</dd></div></dl>}{node.toc.length>0&&<details className="read-toc"><summary>本页目录 <em>Contents</em></summary>{node.toc.map(h=><a key={h.id} href={`#/doc/${encodeURIComponent(node.id)}/${encodeURIComponent(h.id)}`}>{h.title}</a>)}</details>}{article}{copy&&<p role="status">{copy}</p>}<div className="read-connections"><h3>文档引用 <em>References</em></h3>{follow(node.references.map(r=>r.id))}<h3>反向引用 <em>Backlinks</em></h3>{follow(node.backlinks)}{node.issues.length>0&&<p className="quiet">未解析引用：{node.issues.map(i=>i.target+'（'+i.reason+'）').join('、')}</p>}</div><p className="read-path">{node.path}</p></div><LinkPreview readerRef={ref} graph={graph} onPreview={onPreview}/></section>;
}
