import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CONFIG,asset} from '../config';
import {buildGraph,forceLayout,MODULES,moduleOf} from './graph';
import {Home} from './Home';
import {Icon} from './icons';
import {T} from './theme';
import './neural.css';
import './documents.css';
const staticPages=typeof __STATIC_PAGES__!=='undefined'&&__STATIC_PAGES__;
function App(){
 const [library,setLibrary]=useState(null),[error,setError]=useState(''),[focus,updateFocus]=useState({mod:null,sel:null}),[panel,setPanel]=useState(null),[search,setSearch]=useState('');
 const reduced=useMemo(()=>matchMedia('(prefers-reduced-motion: reduce)').matches,[]);
 useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch(staticPages?import.meta.env.BASE_URL+'library.json':'/api/library');if(!r.ok)throw Error('无法读取文档');const next=await r.json();if(active)setLibrary(old=>old?.version===next.version?old:next);}catch(e){if(active)setError(e.message);}};load();const timer=staticPages?null:setInterval(()=>{if(!document.hidden)load();},4000);return()=>{active=false;clearInterval(timer);};},[]);
 const graph=useMemo(()=>library?buildGraph(library):null,[library]);const layout=useMemo(()=>graph?forceLayout(graph):{},[graph]);
 const setFocus=useCallback(next=>{updateFocus(next);history.pushState(null,'',next.sel?'#/doc/'+encodeURIComponent(next.sel):next.mod?'#/module/'+next.mod:'#/');},[]);
 useEffect(()=>{if(!graph)return;const route=()=>{const parts=location.hash.replace(/^#\//,'').split('/');if(parts[0]==='doc'){const node=graph.index.get(decodeURIComponent(parts[1]||''));updateFocus(node?.module?{mod:moduleOf(node).id,sel:node.id}:{mod:null,sel:null});}else if(parts[0]==='module'){updateFocus({mod:MODULES.some(m=>m.id===parts[1])?parts[1]:null,sel:null});}else updateFocus({mod:null,sel:null});};route();window.addEventListener('hashchange',route);window.addEventListener('popstate',route);return()=>{window.removeEventListener('hashchange',route);window.removeEventListener('popstate',route);};},[graph]);
 useEffect(()=>{if(!panel)return;const key=e=>{if(e.key==='Escape')setPanel(null);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[panel]);
 const go=id=>{const n=graph.index.get(id);if(!n?.module)return;setPanel(null);setFocus({mod:moduleOf(n).id,sel:id});};
 if(!graph)return <div className="neural loading-screen">{error||'正在展开知识星云…'}</div>;
 const list=library.documents.filter(d=>(panel!=='maps'||d.type==='map')&&[d.title,...d.aliases,...d.tags,d.body].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <div className="neural page-home"><header className="topbar"><a className="brand" href="#/" onClick={e=>{e.preventDefault();setPanel(null);setFocus({mod:null,sel:null});}}><span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 24 28" width="18" height="21"><path fill={T.logo[0]} d="m14 1 8 7-2 12-7 7-10-5L1 12 8 4Z"/><path fill={T.logo[1]} d="m14 1-3 10 2 16 7-7 2-12Z"/><path fill={T.logo[2]} d="m14 1-3 10 11-3Z"/><path fill={T.logo[3]} d="m1 12 10-1 2 16-10-5Z"/></svg></span><span className="brand-text">{CONFIG.brand.name}<b>/ {CONFIG.brand.sub}</b><small>{staticPages?'公开知识星云':CONFIG.brand.tagline} · {CONFIG.brand.taglineEn}</small></span></a><nav aria-label="页面导航"><button className={!panel?'active':''} onClick={()=>setPanel(null)}>知识星云<em>Cosmos</em></button><button className={panel==='documents'?'active':''} onClick={()=>{setSearch('');setPanel('documents');}}>文档<em>Documents</em></button><button className={panel==='maps'?'active':''} onClick={()=>{setSearch('');setPanel('maps');}}>阅读地图<em>Maps</em></button></nav><div className="top-actions"><span className="pill ghost">{staticPages?'公开文档 · 只读':'本地 · 私人 · 只读'}</span><button className="avatar" onClick={()=>go('index')} aria-label="打开知识导航"><img src={asset('avatar.svg')} alt=""/></button></div></header><Home graph={graph} layout={layout} focus={focus} setFocus={setFocus} reduced={reduced} onAbout={()=>setPanel('about')}/>{panel&&<div className="veil" onClick={()=>setPanel(null)}><section className="modal glass document-browser" role="dialog" aria-modal="true" aria-label={panel==='about'?'页面说明':'文档列表'} onClick={e=>e.stopPropagation()}><header><h2>{panel==='maps'?'阅读地图':panel==='about'?'关于知识星云':'全部文档'}</h2><button className="icon-btn" onClick={()=>setPanel(null)} aria-label="关闭列表"><Icon name="close" size={16}/></button></header>{panel==='about'?<div className="about-body"><p>{staticPages?'展示公开清单中获准的文档。':'直接读取本地 content/notes 与 content/maps，文件修改后自动同步。'}主题归属与正文引用分别展示。</p><p>场景基于 Neural Creator Dashboard，保留原项目的光球、弹簧过渡、粒子、流光连线和分层展开；水母素材替换为星云。</p><p>{staticPages?'该页面公开展示获准发布的文档。':'文档默认为私人，只在本机访问。'}此页面没有创作数据、账号指标、草稿编辑或选题管理。</p><p><a href="https://github.com/luoluo-121/neural-creator-dashboard" target="_blank" rel="noopener noreferrer">原项目与作者：luoluo-121 ↗</a></p><p className="quiet">PolyForm Noncommercial 1.0.0；完整署名及历史授权见应用目录的 LICENSE、NOTICE.md 与 licenses/。</p></div>:<><label className="browser-search"><Icon name="search" size={16}/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索标题、别名或正文" aria-label="搜索文档列表"/></label><div className="browser-documents">{list.map(d=><button key={d.id} onClick={()=>go(d.id)}><span>{d.title}</span><small>{d.summary}</small></button>)}{!list.length&&<p className="quiet">没有找到匹配的文档</p>}</div></>}</section></div>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
